services:
  db:
    image: postgres:16-alpine
    container_name: padelapp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: padelapp
      POSTGRES_PASSWORD: padelapp
      POSTGRES_DB: padelapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U padelapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
