-- AlterTable
ALTER TABLE "User" ADD COLUMN     "attendanceScore" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "lastMatchAt" TIMESTAMP(3),
ADD COLUMN     "losses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "matchesPlayed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rankingDelta" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rankingPosition" INTEGER,
ADD COLUMN     "rankingScore" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN     "wins" INTEGER NOT NULL DEFAULT 0;
